# This is the main workflow that creates a new image and push to Openshift image stream which in turn triggers the deployment

name: Main - Build Image and Push to Openshift Registry for Dev Deployment

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
        app:
            description: 'App Name (bc-paris-api)'    
            required: true
            default: bc-paris-api
        env:
            description: 'Image Target Env'     
            required: true
            default: 'dev'

jobs:

  app-version:
    uses: SierraSystems/reusable-workflows/.github/workflows/java-maven-app-version.yml@main
    with:
      working_directory: .

  build-image:
    uses: SierraSystems/reusable-workflows/.github/workflows/openshift-source-to-image.yml@main
    with:
      build_config_name: ${{ github.event.inputs.app }}
      image_tags: ${{ github.event.inputs.env }}
    secrets:
      openshift_namespace: ${{ secrets.OPENSHIFT_LICENSE_PLATE_SILVER }}-tools
      openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL_SILVER }}
      openshift_token: ${{ secrets.OPENSHIFT_SA_PIPELINE_TOKEN_SILVER }}
      openshift_external_repository: ${{ secrets.OPENSHIFT_EXTERNAL_REPOSITORY_SILVER }}
