# Creates a new image and push to Openshift image stream & also scan for vulnerabilities

name: Trivy Scan

on:
  workflow_dispatch:

jobs:
  build-scan:
    name: Build & Scan Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

          # Set up JDK build environment
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      # Runs build steps
      - name: Maven Package
        run: mvn -ntp clean verify

      #Build image jag-ccd-1-1
      - name: Build image bcparis
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
          CONTEXT: .
        run: |
          docker build -t bcparis-scan ${CONTEXT}

      - name: Run Trivy vulnerability scanner - stdout
        uses: ekwanNTT/trivy-action@master
        with:
          scan-type: image
          image-ref: bcparis-scan
          format: table
          exit-code: '1'
          ignore-unfixed: true
          severity: HIGH,CRITICAL

      - name: Run Trivy vulnerability scanner - save-result to file
        uses: ekwanNTT/trivy-action@master
        with:
          scan-type: image
          image-ref: bcparis-scan
          format: template
          template: '@/contrib/sarif.tpl'
          output: trivy-results.sarif
          exit-code: '1'
          ignore-unfixed: true
          severity: HIGH,CRITICAL

      #Upload results to the GitHub Security Tab.
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        if: always()
        with:
          sarif_file: trivy-results.sarif

