# This workflow is used to build & scan image using trivy vulnerability scanner and upload the results to github security tab

name: Build & Vulnerability Scan using Trivy Scanner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    branches: [main, feature/devopsupgrade]

jobs:

  build-push-image:
    uses: SierraSystems/reusable-workflows/.github/workflows/trivy-scanning-s2i.yml@feature/devopsupgrade
    with:
      build_config_name: bc-paris-api-trivy
      imagestream_name: bc-paris-api
      source_image_tag: trivy
    secrets:
      openshift_namespace: ${{ secrets.OPENSHIFT_LICENSE_PLATE_SILVER }}-tools
      openshift_sa_name: ${{ secrets.OPENSHIFT_SA_NAME }}
      openshift_sa_password: ${{ secrets.OPENSHIFT_SA_PASSWORD }}
      openshift_external_repository: ${{ secrets.OPENSHIFT_EXTERNAL_REPOSITORY_SILVER }}
